//! Fixed known-answer tests (the `addr_type` axis included).
//! KAT policy — `specs/spec.md` «Качество и CI» (KAT).
//!
//! `tests/kat/vectors.json` is generated by `tests/kat/generate.py`
//! against the `yubtc-python` reference (KDF backport commit e3f6cd3;
//! SegWit mirror branch `issue-segwit`, commit recorded in the file's
//! `reference_commit`), which implements all four KDFs plus the three
//! address forms and is the bit-for-bit oracle for every row -- the
//! generator carries no stretch code of its own.
//!
//! Every row must reproduce bit-for-bit through the whole Rust
//! pipeline: `seed2bin` → `seed2privkey_with_kdf` → mainnet addresses
//! → WIF. Each row additionally pins the `address_forms`
//! axis through the wallet-level constructor
//! [`TPrivKey::with_addr_type`]:
//!
//! - `yubtc` / `argon2id` / `scrypt` (вариант A, spec ОВ-2): the same
//!   key in three encodings (P2PKH / P2WPKH / P2TR TapTweak) -- the
//!   per-form `privkey`/`wif` are byte-identical to the row's;
//! - `pbkdf2` (BIP-39-compatible): purpose-specific keys
//!   (`m/44'…` / `m/84'…` / `m/86'…`), so all three keys, addresses
//!   and WIFs differ.
//!
//! 100% of the vector file is exercised: the loop asserts all four
//! legacy outputs plus all three address forms of every row, and the
//! tail asserts the file still covers the full 4 KDFs × 2 nonces ×
//! 2 seeds matrix, so a truncated regeneration fails here instead of
//! silently shrinking the fence.

use std::collections::HashSet;

use serde::Deserialize;
use yubtc_core::address::privkey_to_wif;
use yubtc_core::kdf::{seed2bin, KdfAlgo};
use yubtc_core::misc::{TNonce, TPassphrase, TSeed};
use yubtc_core::wallet::{AddrType, TPrivKey};

#[derive(Debug, Deserialize)]
struct KatForm {
    addr_type: String,
    privkey: String,
    address: String,
    wif: String,
}

#[derive(Debug, Deserialize)]
struct KatVector {
    seed: String,
    nonce: u32,
    passphrase: String,
    kdf: String,
    seed2bin: String,
    privkey: String,
    address: String,
    wif: String,
    address_forms: std::collections::HashMap<String, KatForm>,
}

#[derive(Debug, Deserialize)]
struct KatFile {
    vector_count: usize,
    vectors: Vec<KatVector>,
}

fn parse_kdf(s: &str) -> KdfAlgo {
    match s {
        "yubtc" => KdfAlgo::Yubtc,
        "pbkdf2" => KdfAlgo::Pbkdf2,
        "argon2id" => KdfAlgo::Argon2id,
        "scrypt" => KdfAlgo::Scrypt,
        other => panic!("unknown kdf in vectors.json: {other}"),
    }
}

fn parse_addr_type(s: &str) -> AddrType {
    match s {
        "legacy" => AddrType::Legacy,
        "native" => AddrType::Native,
        "taproot" => AddrType::Taproot,
        other => panic!("unknown addr_type in vectors.json: {other}"),
    }
}

// 16 rows, each of the 8 memory-hard rows costing ~15-20s in the debug
// profile (64 MiB stretch); 180s measured locally, so allow generous
// headroom for slower CI machines.
#[ntest_timeout::timeout(600_000)]
#[test]
fn kat_vectors_match_reference() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("kat")
        .join("vectors.json");
    let raw = std::fs::read_to_string(&path).expect(
        "core/tests/kat/vectors.json is checked in next to this test; \
         regenerate with core/tests/kat/generate.py",
    );
    let kat: KatFile = serde_json::from_str(&raw).expect("vectors.json parses as the KAT schema");
    assert_eq!(
        kat.vectors.len(),
        kat.vector_count,
        "vector_count must match the vectors array length"
    );

    let mut seen_kdfs: HashSet<KdfAlgo> = HashSet::new();
    let mut seen_combos: HashSet<(String, u32, String)> = HashSet::new();

    for (idx, v) in kat.vectors.iter().enumerate() {
        let kdf = parse_kdf(&v.kdf);
        let seed = TSeed::new(v.seed.clone());
        let nonce = TNonce::new(v.nonce);
        let pass = TPassphrase::new(v.passphrase.clone());
        seen_kdfs.insert(kdf);
        assert!(
            seen_combos.insert((v.kdf.clone(), v.nonce, v.seed.clone())),
            "duplicate (kdf, nonce, seed) combo at vector {idx}"
        );

        // 1. KDF output, bit-for-bit.
        let bin = seed2bin(&seed, nonce, &pass, kdf)
            .expect("KAT rows only contain valid (kdf, passphrase) combos");
        assert_eq!(
            hex::encode(bin),
            v.seed2bin,
            "seed2bin mismatch at vector {idx} (kdf={}, nonce={})",
            v.kdf,
            v.nonce
        );

        // 2-5. The three address forms through the wallet-level
        // constructor. For pbkdf2 every form is its own purpose
        // key; for the other KDFs all three forms derive the same
        // key (вариант A) — exactly what `with_addr_type`
        // implements, so a purpose/encoding drift in the wallet
        // layer fails here against the Python oracle.
        assert_eq!(
            v.address_forms.len(),
            3,
            "vector {idx} must carry all three address forms"
        );
        for (form_name, form) in &v.address_forms {
            let addr_type = parse_addr_type(form_name);
            assert_eq!(
                form.addr_type, *form_name,
                "form key and addr_type disagree at vector {idx}"
            );
            let pk = TPrivKey::with_addr_type(&seed, nonce, &pass, kdf, addr_type)
                .expect("KAT rows only contain valid (kdf, addr_type) combos");
            assert_eq!(
                hex::encode(pk.privkey.to_bytes()),
                form.privkey,
                "form privkey mismatch at vector {idx} ({form_name})"
            );
            assert_eq!(
                pk.address.as_str(),
                form.address,
                "form address mismatch at vector {idx} ({form_name})"
            );
            assert_eq!(
                privkey_to_wif(&pk.privkey),
                form.wif,
                "form wif mismatch at vector {idx} ({form_name})"
            );
        }

        // 6. The pre-existing row fields stay pinned: privkey and
        // legacy address/WIF must equal the row's legacy form.
        let legacy = &v.address_forms["legacy"];
        assert_eq!(
            legacy.privkey, v.privkey,
            "legacy form drift at vector {idx}"
        );
        assert_eq!(
            legacy.address, v.address,
            "legacy address drift at vector {idx}"
        );
        assert_eq!(legacy.wif, v.wif, "legacy wif drift at vector {idx}");

        // 7. Variant-A invariant for the non-BIP-32 KDFs: one key,
        // three encodings — every form's privkey is the row key.
        // For pbkdf2 the forms are distinct purpose keys.
        if kdf == KdfAlgo::Pbkdf2 {
            let keys: HashSet<&str> = v
                .address_forms
                .values()
                .map(|f| f.privkey.as_str())
                .collect();
            assert_eq!(
                keys.len(),
                3,
                "pbkdf2 forms must use distinct purpose keys at vector {idx}"
            );
        } else {
            for (form_name, form) in &v.address_forms {
                assert_eq!(
                    form.privkey, v.privkey,
                    "variant A: {form_name} must reuse the row key at vector {idx}"
                );
            }
        }
    }

    // Coverage fence: all four KDFs, each at 2 nonces × 2 seeds. The
    // passphrase is forced by the kdf (empty for yubtc, non-empty for
    // the rest — see generate.py), so the (kdf, nonce, seed) triple
    // identifies the row uniquely.
    assert_eq!(seen_kdfs.len(), 4, "vectors.json must cover all 4 KDFs");
    assert_eq!(
        seen_combos.len(),
        16,
        "expected the full 4 KDFs × 2 nonces × 2 seeds matrix"
    );
}
