//! Fixed known-answer tests for the multi-sig (P2SH) quorum surface
//! (Phase 15, per the `psbt_vectors.rs` precedent).
//!
//! `tests/kat/ms_vectors.json` is generated by
//! `tests/kat/generate.py --axis ms` against the `yubtc-python`
//! multi-sig mirror (the bit-for-bit oracle; `reference_commit`
//! records the mirror commit, 8995d9c at generation time) — the
//! generator carries no quorum or pipeline code of its own.
//!
//! 16 rows, one per (seed, own_nonce) tuple of the mirror's
//! multi-sig fixture family (`tests/test_multisig.py`: seeds
//! `phase15multisig` / `phase15wallet`, cascade KDF, empty
//! passphrase). Each row is a `(N, M, keys, nonce)` tuple: the own
//! legacy-form key at `own_nonce` plus the cosigner keys at the row's
//! `key_nonces` — all derived from the row seed — passed to the
//! wallet-level `ms_create_address` in the row's rotated order
//! (R-MS-4: unsorted input, canonical sorted output). Every row pins
//! the quorum constants (`address`, `redeem_hex`,
//! `script_pubkey_hex`) and the 2-of-3 five-stage PSBT pipeline
//! through the mirror's P2SH-multisig Creator/Signer/Combiner/
//! Finalizer/Extractor branches: `unsigned → signed_a (own key) →
//! combined (first cosigner) → signed_ab/combined → finalized →
//! wire_hex`, plus the display `txid` and the finalized `scriptSig`
//! length. The prev tx pays 60 000 sat to the quorum address
//! ([0x22; 32] outpoint); the spend targets the row seed's
//! native-P2WPKH key at nonce 9 for 50 000 sat.
//!
//! The anchor row (`phase15multisig`, own_nonce 0) equals the
//! mirror's `tests/test_multisig.py::MS_ROWS` parity rows
//! bit-for-bit; its finalized `scriptSig` is exactly 253 bytes —
//! the D-002 CompactSize pin (`fd fd 00` at wire bytes 41..44, the
//! first yubtc script past the LEB128 divergence point).
//!
//! v0.3 adds the witness-form arrays of the SAME 16 tuples:
//!
//! * **P2WSH** (`witness_vectors`, `form = "p2wsh"`): `bc1q…` v0/32
//!   `SHA256(redeem)` commitment, byte-identical redeem script,
//!   BIP-143 Signer over the witness script, the BIP-141 stack
//!   `[empty dummy, M sigs, redeem]` (`witness_items = M + 2 = 4`).
//! * **P2TR script-path** (`tapscript_vectors`, `form = "p2tr"`):
//!   the R-MS-7 `CHECKSIGADD` tapscript over the x-only key
//!   projections (a *different* script than the p2sh/p2wsh redeem,
//!   R-MS-10), the `bc1p…` bech32m v1 commitment to the tweaked NUMS
//!   output key, the BIP-341 script-path Signer (untweaked BIP-340
//!   Schnorr, SIGHASH_DEFAULT) and the R-MS-11 Finalizer stack
//!   `[N reversed sig slots, tapscript, 33-byte control block]`
//!   (`witness_items = N + 2 = 5`, `final_scriptwitness_len = 271`).
//!   Each row additionally pins the crypto chain between the
//!   tapscript and the address — the NUMS internal key, the leaf
//!   hash, the tweaked output key, the control block — plus the own
//!   signer's script-path digest (`sighash_hex`) and the
//!   deterministic signature (`own_sig_hex`). The rows mirror the
//!   Python parity fixture `tests/fixtures/tapscript_ms_rows.json`
//!   row for row.
//!
//! Every row must reproduce bit-for-bit through the Rust surface:
//! `ms_create_address` (canonical quorum constants) →
//! `PartiallySignedTransaction::create` (the per-form Creator branch:
//! P2SH `NON_WITNESS_UTXO` + `REDEEM_SCRIPT`; P2WSH `WITNESS_UTXO` +
//! `WITNESS_SCRIPT`; P2TR `WITNESS_UTXO` + `TAP_LEAF_SCRIPT` +
//! `TAP_INTERNAL_KEY`) → `sign_input` with the own key → `sign_input`
//! with a cosigner key on a fresh copy → `combine` → `finalize` →
//! `extract_transaction`, byte-equal at every pinned stage.
//!
//! 100% of the vector file is exercised: the loop asserts all stage
//! strings, both quorum constants, the crypto-chain pins (p2tr), the
//! txid and the finalized-input length of every row; the tail fences
//! the full matrix (2 seeds × 8 own-nonces, cascade KDF, 2-of-3
//! shape, unique tuples) across all three forms — 48 rows, 16 tuples
//! × {p2sh, p2wsh, p2tr} — the anchor's 253-byte CompactSize pin, the
//! p2tr anchor's control block / witness stack and the recorded
//! reference commit — a truncated or re-pinned regeneration fails
//! here instead of silently shrinking the fence.

use std::collections::HashSet;

use k256::ecdsa::SigningKey;
use serde::Deserialize;
use yubtc_core::kdf::KdfAlgo;
use yubtc_core::misc::{TNonce, TPassphrase, TSeed};
use yubtc_core::privkey::{privkey_to_pubkey, seed2privkey_with_kdf};
use yubtc_core::psbt::{CreateInput, PartiallySignedTransaction};
use yubtc_core::transaction::{Transaction, TxIn, TxOut};
use yubtc_core::wallet::{derive_script, ms_create_address, AddrType};

#[derive(Debug, Deserialize)]
struct MsVector {
    name: String,
    seed: String,
    kdf: String,
    own_nonce: u32,
    key_nonces: Vec<u32>,
    n: u32,
    m: u32,
    dst_nonce: u32,
    dst_form: String,
    /// The quorum address form: `"p2sh"` (the Phase 15 rows) or
    /// `"p2wsh"` (the v0.3 witness rows). Optional for backward
    /// compatibility with the pre-v0.3 file shape.
    #[serde(default = "default_form")]
    form: String,
    redeem_hex: String,
    address: String,
    script_pubkey_hex: String,
    unsigned: String,
    signed_a: String,
    signed_ab: String,
    combined: String,
    finalized: String,
    wire_hex: String,
    txid: String,
    #[serde(default)]
    scriptsig_len: usize,
    /// The BIP-141 item count of the finalized witness stack
    /// (`M + 2`); present on the v0.3 witness rows only.
    #[serde(default)]
    witness_items: usize,
    /// The NUMS internal key of the p2tr commitment
    /// (`SHA256(uncompressed G)`); tapscript rows only.
    #[serde(default)]
    internal_hex: String,
    /// `hashTapLeaf` of the row's tapscript; tapscript rows only.
    #[serde(default)]
    leaf_hash_hex: String,
    /// The tweaked NUMS output key `Q` (the address program);
    /// tapscript rows only.
    #[serde(default)]
    output_key_hex: String,
    /// The BIP-341 control block (`c[0] ‖ internal key`, 33 bytes);
    /// tapscript rows only.
    #[serde(default)]
    control_hex: String,
    /// The own signer's BIP-341 script-path digest (SIGHASH_DEFAULT);
    /// tapscript rows only.
    #[serde(default)]
    sighash_hex: String,
    /// The own signer's untweaked BIP-340 signature over `sighash`;
    /// tapscript rows only.
    #[serde(default)]
    own_sig_hex: String,
    /// The finalized witness stack item by item (`[w_N … w_1,
    /// tapscript, control block]`); tapscript rows only.
    #[serde(default)]
    witness_stack_hex: Vec<String>,
    /// The serialized `FINAL_SCRIPTWITNESS` value length
    /// (compact_size count + items = 271 for the 2-of-3 fixture);
    /// tapscript rows only.
    #[serde(default)]
    final_scriptwitness_len: usize,
}

fn default_form() -> String {
    "p2sh".to_string()
}

#[derive(Debug, Deserialize)]
struct MsKatFile {
    reference_commit: String,
    vector_count: usize,
    vectors: Vec<MsVector>,
    anchor: Anchor,
    /// The v0.3 witness rows (the same 16 tuples in the native P2WSH
    /// form). Optional for backward compatibility.
    #[serde(default)]
    witness_vectors: Vec<MsVector>,
    #[serde(default)]
    witness_anchor: Option<Anchor>,
    /// The v0.3 tapscript rows (the same 16 tuples in the P2TR
    /// script-path form). Optional for backward compatibility.
    #[serde(default)]
    tapscript_vectors: Vec<MsVector>,
    #[serde(default)]
    tapscript_anchor: Option<Anchor>,
}

#[derive(Debug, Deserialize)]
struct Anchor {
    seed: String,
    own_nonce: u32,
}

fn parse_kdf(s: &str) -> KdfAlgo {
    match s {
        "yubtc" => KdfAlgo::Yubtc,
        "pbkdf2" => KdfAlgo::Pbkdf2,
        "argon2id" => KdfAlgo::Argon2id,
        "scrypt" => KdfAlgo::Scrypt,
        other => panic!("unknown kdf in ms_vectors.json: {other}"),
    }
}

/// Replay one row through the Rust quorum surface: `ms_create_address`
/// → Creator → Signer (own) → Signer (cosigner, fresh copy) →
/// Combiner → Finalizer → Extractor, byte-equal at every pinned
/// stage. `v.form` selects the address/spend encoding: `"p2sh"`
/// (Phase 15 — legacy `scriptSig` spend, `NON_WITNESS_UTXO` +
/// `REDEEM_SCRIPT`), `"p2wsh"` (v0.3 — BIP-141 witness spend,
/// `WITNESS_UTXO` + `WITNESS_SCRIPT`, no prev-tx fetch) or `"p2tr"`
/// (v0.3 — script-path spend, `WITNESS_UTXO` + `TAP_LEAF_SCRIPT` +
/// `TAP_INTERNAL_KEY`, the pinned BIP-341 digest / untweaked
/// signature chain and the R-MS-11 Finalizer stack).
fn replay_row(v: &MsVector) {
    let kdf = parse_kdf(&v.kdf);
    let seed = TSeed::new(v.seed.clone());
    let pass = TPassphrase::EMPTY;
    let key_at = |nonce: u32| -> SigningKey {
        seed2privkey_with_kdf(&seed, TNonce::new(nonce), &pass, kdf)
            .unwrap_or_else(|e| panic!("row {}: key {nonce} derives: {e}", v.name))
    };
    let form = match v.form.as_str() {
        "p2sh" => yubtc_core::wallet::MsForm::P2sh,
        "p2wsh" => yubtc_core::wallet::MsForm::P2wsh,
        "p2tr" => yubtc_core::wallet::MsForm::P2tr,
        other => panic!("row {}: unknown form {other}", v.name),
    };

    // 1. Quorum constants: the keys in the row's (rotated) input
    //    order — `ms_create_address` sorts (R-MS-4) — must reproduce
    //    the pinned canonical address and redeem script.
    let keys: Vec<[u8; 33]> = v
        .key_nonces
        .iter()
        .map(|&n| privkey_to_pubkey(&key_at(n)))
        .collect();
    let (addr, redeem) = ms_create_address(v.n as usize, v.m as usize, &keys, form)
        .unwrap_or_else(|e| panic!("row {}: quorum derives: {e}", v.name));
    assert_eq!(addr.as_str(), v.address, "address mismatch at {}", v.name);
    assert_eq!(
        hex::encode(&redeem),
        v.redeem_hex,
        "redeem script mismatch at {}",
        v.name
    );

    // 2. Creator fixture: prev tx paying the quorum address, spend to
    //    the row seed's native-P2WPKH at dst_nonce; the P2SH branch
    //    writes NON_WITNESS_UTXO + REDEEM_SCRIPT, the P2WSH branch
    //    WITNESS_UTXO + WITNESS_SCRIPT (no prev-tx fetch).
    // The per-form quorum lock script — the shared Creator-side
    // helper (p2sh hash160, p2wsh SHA-256, p2tr tweaked NUMS output
    // key), so the replay cannot drift from the wallet Creator.
    let spk = yubtc_core::wallet::ms_quorum_lock_script(&redeem, form);
    assert_eq!(
        hex::encode(&spk),
        v.script_pubkey_hex,
        "scriptPubKey mismatch at {}",
        v.name
    );

    // The p2tr crypto chain: NUMS internal key → leaf hash → tweaked
    // output key → control block — the pinned path from the tapscript
    // redeem to the `bc1p` commitment; the lock script must embed
    // exactly the tweaked output key.
    let p2tr = if form == yubtc_core::wallet::MsForm::P2tr {
        assert_eq!(
            hex::encode(yubtc_core::fwd::MS_TAPSCRIPT_INTERNAL_KEY),
            v.internal_hex,
            "NUMS internal key mismatch at {}",
            v.name
        );
        let leaf_hash = yubtc_core::script::tapscript_leaf_hash(&redeem);
        assert_eq!(
            hex::encode(leaf_hash),
            v.leaf_hash_hex,
            "leaf hash mismatch at {}",
            v.name
        );
        let output_key = yubtc_core::address::tapscript_output_key(
            &yubtc_core::fwd::MS_TAPSCRIPT_INTERNAL_KEY,
            &leaf_hash,
        )
        .expect("the NUMS tweak is total");
        assert_eq!(
            hex::encode(output_key),
            v.output_key_hex,
            "output key mismatch at {}",
            v.name
        );
        let control = yubtc_core::address::tapscript_control_block(
            &yubtc_core::fwd::MS_TAPSCRIPT_INTERNAL_KEY,
            &leaf_hash,
        )
        .expect("the NUMS control block is total");
        assert_eq!(
            control.len(),
            33,
            "row {}: control block is 33 bytes",
            v.name
        );
        assert_eq!(
            hex::encode(control),
            v.control_hex,
            "control block mismatch at {}",
            v.name
        );
        assert_eq!(
            spk,
            [0x51u8, 0x20]
                .iter()
                .copied()
                .chain(output_key)
                .collect::<Vec<u8>>(),
            "row {}: the lock script embeds the tweaked output key",
            v.name
        );
        Some((leaf_hash, control))
    } else {
        None
    };
    assert_eq!(v.dst_form, "native", "row {}: fixture dst form", v.name);
    let dst_spk = derive_script(
        &seed,
        TNonce::new(v.dst_nonce),
        &pass,
        kdf,
        AddrType::Native,
    )
    .expect("fixture dst derives");
    let prev = Transaction {
        version: 2,
        vin: vec![TxIn {
            txhash: [0x22; 32],
            n: 0,
            script: vec![],
            sequence: 0xffff_ffff,
            witness: Vec::new(),
        }],
        vout: vec![TxOut {
            amount: 60_000,
            script: spk.clone(),
        }],
        locktime: 0,
    };
    let unsigned_tx = Transaction {
        version: 2,
        vin: vec![TxIn {
            // The P2SH rows spend the fixture prev tx; the witness
            // rows (p2wsh / p2tr) carry a synthetic outpoint (no
            // prev-tx fetch).
            txhash: if form == yubtc_core::wallet::MsForm::P2sh {
                prev.id()
            } else {
                [0x44; 32]
            },
            n: 0,
            script: vec![],
            sequence: 0xffff_fffe,
            witness: Vec::new(),
        }],
        vout: vec![TxOut {
            amount: 50_000,
            script: dst_spk,
        }],
        locktime: 0,
    };
    let build = || {
        PartiallySignedTransaction::create(
            unsigned_tx.clone(),
            vec![if form == yubtc_core::wallet::MsForm::P2sh {
                CreateInput {
                    amount: 60_000,
                    script_pubkey: spk.clone(),
                    prev_tx: Some(prev.clone()),
                    redeem_script: Some(redeem.clone()),
                    witness_script: None,
                    tap_leaf_script: None,
                }
            } else {
                // Witness forms: p2wsh carries the witness script,
                // p2tr the tap leaf; both skip the prev-tx fetch.
                CreateInput {
                    amount: 60_000,
                    script_pubkey: spk.clone(),
                    prev_tx: None,
                    redeem_script: None,
                    witness_script: (form == yubtc_core::wallet::MsForm::P2wsh)
                        .then(|| redeem.clone()),
                    tap_leaf_script: (form == yubtc_core::wallet::MsForm::P2tr).then_some({
                        let mut leaf = redeem.clone();
                        leaf.push(yubtc_core::script::TAPSCRIPT_LEAF_VERSION);
                        leaf
                    }),
                }
            }],
        )
        .expect("fixture PSBT builds")
    };

    // 3. Unsigned stage: the Creator container is canonical (parse →
    //    serialize round-trips byte-for-byte).
    let mut psbt_a = build();
    assert_eq!(
        psbt_a.to_base64(),
        v.unsigned,
        "unsigned stage mismatch at {}",
        v.name
    );

    // 4. Signer A: the own key at own_nonce (R-MS-6 legacy form)
    //    signs by quorum membership.
    assert!(
        psbt_a
            .sign_input(0, &key_at(v.own_nonce))
            .expect("own member signs"),
        "row {}: the own key must sign the quorum input",
        v.name
    );
    assert_eq!(
        psbt_a.to_base64(),
        v.signed_a,
        "signed_a stage mismatch at {}",
        v.name
    );
    if let Some((leaf_hash, _control)) = &p2tr {
        // The pinned script-path digest (BIP-341, spend_type 0x02,
        // SIGHASH_DEFAULT) and the deterministic untweaked BIP-340
        // signature the Signer inserted for it.
        let sighash = yubtc_core::transaction::taproot_scriptpath_sighash(
            &unsigned_tx,
            0,
            &yubtc_core::transaction::SpendContext {
                inputs: vec![yubtc_core::transaction::SpendInput {
                    amount: 60_000,
                    script_pubkey: spk.clone(),
                }],
            },
            leaf_hash,
        )
        .expect("script-path sighash derives");
        assert_eq!(
            hex::encode(sighash),
            v.sighash_hex,
            "sighash mismatch at {}",
            v.name
        );
        let own_sig =
            yubtc_core::transaction::taproot_sign_sighash_untweaked(&key_at(v.own_nonce), &sighash);
        assert_eq!(
            hex::encode(own_sig),
            v.own_sig_hex,
            "own signature mismatch at {}",
            v.name
        );
        let own_xonly: [u8; 32] = privkey_to_pubkey(&key_at(v.own_nonce))[1..33]
            .try_into()
            .expect("x-only projection");
        assert!(
            psbt_a.inputs[0]
                .tap_script_sigs
                .iter()
                .any(|s| s.x_only == own_xonly
                    && s.leaf_hash == *leaf_hash
                    && s.sig == own_sig.to_vec()),
            "row {}: the Signer inserted the pinned TAP_SCRIPT_SIG",
            v.name
        );
    }

    // 5. Signer B: the first cosigner (first non-own entry of the
    //    row's key order) signs a fresh Creator copy; Combiner merges
    //    the disjoint partial sigs.
    let cosigner_nonce = v
        .key_nonces
        .iter()
        .copied()
        .find(|&n| n != v.own_nonce)
        .expect("row carries a cosigner nonce");
    let mut psbt_b = build();
    assert!(
        psbt_b
            .sign_input(0, &key_at(cosigner_nonce))
            .expect("cosigner signs"),
        "row {}: the cosigner key must sign the quorum input",
        v.name
    );
    let mut combined = psbt_a.combine(&psbt_b).expect("disjoint signers combine");
    assert_eq!(
        combined.to_base64(),
        v.signed_ab,
        "signed_ab stage mismatch at {}",
        v.name
    );
    assert_eq!(
        v.signed_ab, v.combined,
        "row {}: combined pins the same container as signed_ab",
        v.name
    );

    // 6. Finalizer: the OP_0 ‖ sigs ‖ redeem scriptSig in script-key
    //    order.
    combined.finalize();
    assert_eq!(
        combined.to_base64(),
        v.finalized,
        "finalized stage mismatch at {}",
        v.name
    );
    if p2tr.is_some() {
        // The serialized FINAL_SCRIPTWITNESS value (compact_size
        // count + items): 271 bytes for the 2-of-3 fixture.
        let fsw = combined.inputs[0]
            .final_scriptwitness
            .as_deref()
            .expect("a finalized p2tr input carries FINAL_SCRIPTWITNESS");
        assert_eq!(
            fsw.len(),
            v.final_scriptwitness_len,
            "final_scriptwitness length mismatch at {}",
            v.name
        );
    }

    // 7. Extractor: the wire transaction (the payload `yubtc pushtx`
    //    would consume), its display txid and the finalized scriptSig
    //    length.
    let tx = combined
        .extract_transaction()
        .expect("a fully signed+finalized KAT row extracts cleanly");
    assert_eq!(
        hex::encode(tx.serialize_wire()),
        v.wire_hex,
        "extracted wire hex mismatch at {}",
        v.name
    );
    assert_eq!(hex::encode(tx.id()), v.txid, "txid mismatch at {}", v.name);
    if form == yubtc_core::wallet::MsForm::P2sh {
        assert_eq!(
            tx.vin[0].script.len(),
            v.scriptsig_len,
            "scriptSig length mismatch at {}",
            v.name
        );
    } else {
        // Witness forms: empty scriptSig and the row's item count.
        assert!(
            tx.vin[0].script.is_empty(),
            "row {}: the witness spend carries no scriptSig",
            v.name
        );
        assert_eq!(
            tx.vin[0].witness.len(),
            v.witness_items,
            "witness item count mismatch at {}",
            v.name
        );
        if form == yubtc_core::wallet::MsForm::P2wsh {
            // BIP-141: M + 2 witness items, the empty dummy first and
            // the redeem script last (the p2tr pin — N + 2 items with
            // the control block last — arrives with the p2tr rows).
            assert_eq!(v.witness_items, v.m as usize + 2);
            assert!(tx.vin[0].witness[0].is_empty());
            assert_eq!(
                tx.vin[0].witness.last().expect("M + 2 items checked above"),
                &redeem
            );
        } else if let Some((_, control)) = &p2tr {
            // R-MS-11: N + 2 witness items — the N signature slots in
            // reverse script order (exactly N-M non-signers ride
            // empty, no CHECKMULTISIG dummy), the tapscript, the
            // control block.
            assert_eq!(v.witness_items, v.n as usize + 2);
            assert_eq!(
                tx.vin[0].witness.last().expect("N + 2 items checked above"),
                &control.to_vec(),
                "row {}: the control block is the last witness item",
                v.name
            );
            assert_eq!(
                &tx.vin[0].witness[tx.vin[0].witness.len() - 2],
                &redeem,
                "row {}: the tapscript is the second-to-last item",
                v.name
            );
            let stack: Vec<String> = tx.vin[0].witness.iter().map(hex::encode).collect();
            assert_eq!(
                stack, v.witness_stack_hex,
                "witness stack mismatch at {}",
                v.name
            );
            assert_eq!(
                v.witness_stack_hex[..v.n as usize]
                    .iter()
                    .filter(|item| item.is_empty())
                    .count(),
                v.n as usize - v.m as usize,
                "row {}: exactly N-M non-signer slots ride empty",
                v.name
            );
        }
    }
}

// All 16 rows use the cascade KDF (offline derivation) and sign
// once each — the replay is fast even in the debug profile; the
// timeout only guards against a pathological regression.
#[ntest_timeout::timeout(600_000)]
#[test]
fn ms_vectors_match_reference() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("kat")
        .join("ms_vectors.json");
    let raw = std::fs::read_to_string(&path).expect(
        "core/tests/kat/ms_vectors.json is checked in next to this test; \
         regenerate with core/tests/kat/generate.py --axis ms",
    );
    let kat: MsKatFile =
        serde_json::from_str(&raw).expect("ms_vectors.json parses as the KAT schema");
    assert!(
        !kat.reference_commit.is_empty() && kat.reference_commit != "unknown",
        "the reference commit must be recorded (provenance)"
    );
    assert_eq!(
        kat.vectors.len(),
        kat.vector_count,
        "vector_count must match the vectors array length"
    );

    let mut seen_seeds: HashSet<String> = HashSet::new();
    let mut seen_tuples: HashSet<(String, u32)> = HashSet::new();

    for (idx, v) in kat.vectors.iter().enumerate() {
        assert_eq!(
            v.name, "two_of_three",
            "every P2SH row is the 2-of-3 fixture (row {idx})"
        );
        assert_eq!(
            v.kdf, "yubtc",
            "row {idx}: the ms axis pins the cascade fixture family"
        );
        assert_eq!(v.form, "p2sh", "row {idx}: the P2SH array form");
        assert_eq!(v.n, 3, "row {idx}: N = 3");
        assert_eq!(v.m, 2, "row {idx}: M = 2");
        assert_eq!(v.key_nonces.len(), 3, "row {idx}: three derivation nonces");
        assert!(
            v.key_nonces.contains(&v.own_nonce),
            "row {idx}: the own nonce is a quorum member"
        );
        assert!(
            seen_tuples.insert((v.seed.clone(), v.own_nonce)),
            "duplicate (seed, own_nonce) tuple at vector {idx}"
        );
        seen_seeds.insert(v.seed.clone());

        replay_row(v);
    }

    // Coverage fence: the full 2 seeds × 8 own-nonces matrix, each
    // row its own (seed, own_nonce) tuple.
    assert_eq!(
        seen_seeds.len(),
        2,
        "ms_vectors.json must cover both fixture seeds"
    );
    assert_eq!(
        seen_tuples.len(),
        16,
        "expected the full 2 seeds × 8 own-nonces matrix"
    );

    // v0.3: the witness rows replay the SAME 16 tuples in the native
    // P2WSH form — byte-equal at every pinned stage, with the redeem
    // script shared with the P2SH row of the tuple.
    assert_eq!(
        kat.witness_vectors.len(),
        16,
        "expected the 16-row P2WSH witness array (v0.3)"
    );
    let mut seen_witness_tuples: HashSet<(String, u32)> = HashSet::new();
    for (idx, v) in kat.witness_vectors.iter().enumerate() {
        assert_eq!(
            v.name, "two_of_three_witness",
            "every witness row is the v0.3 fixture (row {idx})"
        );
        assert_eq!(v.form, "p2wsh", "row {idx}: the witness array form");
        assert_eq!(v.kdf, "yubtc", "row {idx}: cascade fixture family");
        assert_eq!(v.n, 3, "row {idx}: N = 3");
        assert_eq!(v.m, 2, "row {idx}: M = 2");
        assert!(
            seen_witness_tuples.insert((v.seed.clone(), v.own_nonce)),
            "duplicate (seed, own_nonce) tuple at witness vector {idx}"
        );
        // The witness row shares the redeem script with its P2SH
        // sibling (cross-form parity of the quorum, R-MS-2 decision).
        let sibling = kat
            .vectors
            .iter()
            .find(|p| p.seed == v.seed && p.own_nonce == v.own_nonce)
            .expect("every witness row has a P2SH sibling");
        assert_eq!(
            v.redeem_hex, sibling.redeem_hex,
            "row {idx}: the redeem script is identical in both forms"
        );
        assert_ne!(v.address, sibling.address);

        replay_row(v);
    }
    assert_eq!(
        seen_witness_tuples.len(),
        16,
        "expected the full 2 seeds × 8 own-nonces witness matrix"
    );

    // The anchor row equals the mirror's MS_ROWS parity rows: its
    // finalized scriptSig is the 253-byte D-002 CompactSize pin —
    // wire bytes 41..44 are the script length `fd fd 00`, which a
    // LEB128 encoder would have written as `fd 01`.
    let anchor = kat
        .vectors
        .iter()
        .find(|v| v.seed == kat.anchor.seed && v.own_nonce == kat.anchor.own_nonce)
        .expect("the anchor tuple is part of the matrix");
    assert_eq!(
        anchor.scriptsig_len, 253,
        "the anchor row must carry the 253-byte scriptSig"
    );
    let wire = hex::decode(&anchor.wire_hex).expect("anchor wire hex parses");
    assert_eq!(
        &wire[41..44],
        &[0xfd, 0xfd, 0x00],
        "the anchor wire carries the CompactSize scriptSig length at bytes 41..44"
    );

    // The v0.3 witness anchor: the P2WSH counterpart of the same
    // tuple — same redeem script, a `bc1q` v0 address, a 4-item
    // witness stack.
    let w_anchor_meta = kat
        .witness_anchor
        .as_ref()
        .expect("the v0.3 file records the witness anchor");
    let w_anchor = kat
        .witness_vectors
        .iter()
        .find(|v| v.seed == w_anchor_meta.seed && v.own_nonce == w_anchor_meta.own_nonce)
        .expect("the witness anchor tuple is part of the witness matrix");
    assert_eq!(w_anchor.redeem_hex, anchor.redeem_hex);
    assert!(w_anchor.address.starts_with("bc1q"));
    assert_eq!(w_anchor.witness_items, 4);
    let w_wire = hex::decode(&w_anchor.wire_hex).expect("witness wire hex parses");
    assert_ne!(
        &w_wire[41..44],
        &[0xfd, 0xfd, 0x00],
        "the witness wire carries an empty scriptSig (length 0), not the P2SH push"
    );

    // v0.3: the tapscript rows replay the SAME 16 tuples in the P2TR
    // script-path form — byte-equal at every pinned stage, with the
    // tapscript redeem a *different* script than the p2sh/p2wsh
    // redeems of the tuple (R-MS-10).
    assert_eq!(
        kat.tapscript_vectors.len(),
        16,
        "expected the 16-row P2TR script-path array (v0.3)"
    );
    let mut seen_tap_tuples: HashSet<(String, u32)> = HashSet::new();
    for (idx, v) in kat.tapscript_vectors.iter().enumerate() {
        assert_eq!(
            v.name, "two_of_three_tapscript",
            "every tapscript row is the v0.3 fixture (row {idx})"
        );
        assert_eq!(v.form, "p2tr", "row {idx}: the tapscript array form");
        assert_eq!(v.kdf, "yubtc", "row {idx}: cascade fixture family");
        assert_eq!(v.n, 3, "row {idx}: N = 3");
        assert_eq!(v.m, 2, "row {idx}: M = 2");
        assert_eq!(v.key_nonces.len(), 3, "row {idx}: three derivation nonces");
        assert!(
            seen_tap_tuples.insert((v.seed.clone(), v.own_nonce)),
            "duplicate (seed, own_nonce) tuple at tapscript vector {idx}"
        );
        let sibling = kat
            .vectors
            .iter()
            .find(|p| p.seed == v.seed && p.own_nonce == v.own_nonce)
            .expect("every tapscript row has a P2SH sibling");
        let w_sibling = kat
            .witness_vectors
            .iter()
            .find(|p| p.seed == v.seed && p.own_nonce == v.own_nonce)
            .expect("every tapscript row has a P2WSH sibling");
        assert_ne!(
            v.redeem_hex, sibling.redeem_hex,
            "row {idx}: the tapscript differs from the P2SH redeem (R-MS-10)"
        );
        assert_ne!(
            v.redeem_hex, w_sibling.redeem_hex,
            "row {idx}: the tapscript differs from the P2WSH redeem"
        );
        assert_ne!(v.address, sibling.address);
        assert!(
            v.address.starts_with("bc1p"),
            "row {idx}: the tapscript address is bech32m v1"
        );
        // The full crypto-chain + stack pins must be present on every
        // tapscript row (the replay asserts their values).
        assert!(
            !v.internal_hex.is_empty()
                && !v.leaf_hash_hex.is_empty()
                && !v.output_key_hex.is_empty()
                && !v.control_hex.is_empty()
                && !v.sighash_hex.is_empty()
                && !v.own_sig_hex.is_empty()
                && !v.witness_stack_hex.is_empty(),
            "row {idx}: the tapscript crypto-chain pins are present"
        );
        replay_row(v);
    }
    assert_eq!(
        seen_tap_tuples.len(),
        16,
        "expected the full 2 seeds × 8 own-nonces tapscript matrix"
    );

    // The v0.3 tapscript anchor: the P2TR counterpart of the anchor
    // tuple — tapscript redeem, `bc1p` v1 address, a 5-item stack
    // ending in the 33-byte control block over the NUMS internal key.
    let t_anchor_meta = kat
        .tapscript_anchor
        .as_ref()
        .expect("the v0.3 file records the tapscript anchor");
    let t_anchor = kat
        .tapscript_vectors
        .iter()
        .find(|v| v.seed == t_anchor_meta.seed && v.own_nonce == t_anchor_meta.own_nonce)
        .expect("the tapscript anchor tuple is part of the tapscript matrix");
    assert_ne!(
        t_anchor.redeem_hex, anchor.redeem_hex,
        "the tapscript anchor's redeem differs from the P2SH anchor's"
    );
    let control = hex::decode(&t_anchor.control_hex).expect("anchor control hex parses");
    assert_eq!(control.len(), 33, "the control block is 33 bytes (depth 0)");
    assert_eq!(
        control[0] & 0xfe,
        0xc0,
        "the control byte packs the leaf version and the output-key parity"
    );
    assert_eq!(
        &control[1..33],
        &yubtc_core::fwd::MS_TAPSCRIPT_INTERNAL_KEY[..],
        "the control block reveals the NUMS internal key"
    );
    let stack: Vec<Vec<u8>> = t_anchor
        .witness_stack_hex
        .iter()
        .map(|h| hex::decode(h).expect("witness stack item parses"))
        .collect();
    assert_eq!(stack.len(), 5, "the anchor stack carries N + 2 = 5 items");
    assert_eq!(stack.last().expect("non-empty stack"), &control);
    let anchor_redeem = hex::decode(&t_anchor.redeem_hex).expect("anchor redeem parses");
    assert_eq!(&stack[stack.len() - 2], &anchor_redeem);
    assert_eq!(t_anchor.final_scriptwitness_len, 271);

    // Coverage fence: the SAME 16 tuples across all three forms —
    // 48 rows total, every tuple covered in {p2sh, p2wsh, p2tr}.
    assert_eq!(
        kat.vectors.len() + kat.witness_vectors.len() + kat.tapscript_vectors.len(),
        48,
        "expected 16 tuples × 3 forms (48 rows total)"
    );
    let mut forms: HashSet<&str> = HashSet::new();
    forms.extend(kat.vectors.iter().map(|v| v.form.as_str()));
    forms.extend(kat.witness_vectors.iter().map(|v| v.form.as_str()));
    forms.extend(kat.tapscript_vectors.iter().map(|v| v.form.as_str()));
    assert_eq!(
        forms,
        HashSet::from(["p2sh", "p2wsh", "p2tr"]),
        "all three quorum address forms must be covered"
    );
}
