//! Fixed known-answer tests for the PSBT pipeline (KAT policy —
//! `specs/spec.md` «PSBT — BIP-174» → «Python-зеркало»).
//!
//! `tests/kat/psbt_vectors.json` is generated by
//! `tests/kat/generate.py --axis psbt` against the `yubtc-python`
//! reference (`yubtc.psbt`, the bit-for-bit BIP-174 mirror; the
//! mirror commit is recorded in the file's `reference_commit`,
//! 59bf385 at generation time), which is the oracle for every stage
//! string — the generator carries no pipeline code of its own.
//!
//! 16 rows, one per (seed, passphrase, KDF, nonce) tuple of the
//! address-KAT matrix (`vectors.json`: 4 KDFs × 2 nonces × 2 seeds,
//! passphrase forced by kdf). Every row is the *three-forms* fixture:
//! one legacy P2PKH input (with `NON_WITNESS_UTXO`), one P2WPKH and
//! one P2TR input (each with `WITNESS_UTXO`), all keyed at the row's
//! nonce — so the ОВ-9 Signer nonce walk, all three `SigScheme`s and
//! all three Finalizer layouts are exercised on every tuple.
//!
//! Every row must reproduce bit-for-bit through the Rust roles:
//! `from_base64(unsigned)` → `sign_psbt_with` (walk signs every
//! input) → `finalize` → `extract_transaction`, with the pinned
//! base64 chain and the extracted wire hex equal at each stage.
//!
//! The file additionally carries the two anchored variant rows of the
//! mirror's `tests/test_psbt.py::RUST_ROWS` design:
//!
//! - `unknown_fields`: three opaque pairs injected into the global,
//!   input-1 and output-0 maps before the pipeline — replayed here
//!   byte-for-byte, and the extracted wire transaction must equal
//!   the clean anchor row's (extraction is blind to opaque pairs);
//! - `combine`: `a` = the signed anchor container; `combined` = its
//!   merge with a synthetic disjoint-signer `PARTIAL_SIG`
//!   (33 × 0x02 / 64 × 0xbb) and one extra unknown global pair
//!   (`5107` = `09`) — re-derived here and compared byte-for-byte.
//!
//! 100% of the vector file is exercised: the loop asserts all four
//! stage strings of every row, the tail asserts the file still covers
//! the full 16-tuple matrix (4 KDFs × 2 nonces × 2 seeds) plus both
//! anchored variants, so a truncated regeneration fails here instead
//! of silently shrinking the fence.

use std::collections::HashSet;

use serde::Deserialize;
use yubtc_core::kdf::KdfAlgo;
use yubtc_core::misc::{TPassphrase, TSeed};
use yubtc_core::psbt::{PartiallySignedTransaction, PubKey, UnknownKv};
use yubtc_core::wallet::sign_psbt_with;

#[derive(Debug, Deserialize)]
struct PsbtVector {
    name: String,
    seed: String,
    nonce: u32,
    passphrase: String,
    kdf: String,
    unsigned: String,
    signed: String,
    finalized: String,
    hex: String,
}

#[derive(Debug, Deserialize)]
struct PsbtCombineRow {
    seed: String,
    nonce: u32,
    passphrase: String,
    kdf: String,
    a: String,
    combined: String,
}

#[derive(Debug, Deserialize)]
struct PsbtKatFile {
    reference_commit: String,
    vector_count: usize,
    vectors: Vec<PsbtVector>,
    unknown_fields: PsbtVector,
    combine: PsbtCombineRow,
}

fn parse_kdf(s: &str) -> KdfAlgo {
    match s {
        "yubtc" => KdfAlgo::Yubtc,
        "pbkdf2" => KdfAlgo::Pbkdf2,
        "argon2id" => KdfAlgo::Argon2id,
        "scrypt" => KdfAlgo::Scrypt,
        other => panic!("unknown kdf in psbt_vectors.json: {other}"),
    }
}

/// Replay one row through the Rust roles: Creator container → Signer
/// walk → Finalizer → Extractor, byte-equal at every pinned stage.
/// Returns the finalized PSBT for the caller's extra assertions.
fn replay_row(v: &PsbtVector) -> PartiallySignedTransaction {
    let kdf = parse_kdf(&v.kdf);
    let seed = TSeed::new(v.seed.clone());
    let pass = TPassphrase::new(v.passphrase.clone());

    // 1. Creator stage: the unsigned container parses and is in
    //    canonical form (parse → serialize round-trips byte-for-byte).
    let mut psbt =
        PartiallySignedTransaction::from_base64(&v.unsigned).expect("unsigned container parses");
    assert_eq!(
        psbt.to_base64(),
        v.unsigned,
        "unsigned canonical-form drift at {} ({})",
        v.name,
        v.kdf
    );

    // 2. Signer: the ОВ-9 walk finds and signs every input; the
    //    container — canonical ordering, UTXO fields, ECDSA/Schnorr
    //    partial sigs — is byte-identical to the Python oracle's.
    let unsigned = sign_psbt_with(&seed, &pass, kdf, &mut psbt)
        .expect("the Signer walk only aborts on UtxoMismatch/UnsupportedInputScript");
    assert_eq!(
        unsigned,
        Vec::<usize>::new(),
        "walk left inputs unsigned at {} ({kdf:?}): {unsigned:?}",
        v.name
    );
    assert_eq!(
        psbt.to_base64(),
        v.signed,
        "signed stage mismatch at {} ({})",
        v.name,
        v.kdf
    );

    // 3. Finalizer: the pushed legacy scriptSig / witness stacks.
    psbt.finalize();
    assert_eq!(
        psbt.to_base64(),
        v.finalized,
        "finalized stage mismatch at {} ({})",
        v.name,
        v.kdf
    );

    // 4. Extractor: the wire transaction (BIP-144), hex — the exact
    //    payload `yubtc pushtx` would consume.
    let tx = psbt
        .extract_transaction()
        .expect("a fully signed+finalized KAT row extracts cleanly");
    assert_eq!(
        hex::encode(tx.serialize_wire()),
        v.hex,
        "extracted wire hex mismatch at {} ({})",
        v.name,
        v.kdf
    );
    psbt
}

// The 16 three-forms rows each walk their KDF nonce-by-nonce × 3
// forms (the ОВ-9 walk is the code under test): the nonce-7
// memory-hard rows dominate at ~5.5s per 64 MiB argon2id/scrypt
// stretch in the debug profile — ~108 stretches ≈ 11 min measured
// locally; 30 min gives the same ~3× headroom as the other KAT tests.
#[ntest_timeout::timeout(1_800_000)]
#[test]
fn psbt_vectors_match_reference() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("kat")
        .join("psbt_vectors.json");
    let raw = std::fs::read_to_string(&path).expect(
        "core/tests/kat/psbt_vectors.json is checked in next to this test; \
         regenerate with core/tests/kat/generate.py --axis psbt",
    );
    let kat: PsbtKatFile =
        serde_json::from_str(&raw).expect("psbt_vectors.json parses as the KAT schema");
    assert!(
        !kat.reference_commit.is_empty() && kat.reference_commit != "unknown",
        "the reference commit must be recorded (provenance)"
    );
    assert_eq!(
        kat.vectors.len(),
        kat.vector_count,
        "vector_count must match the vectors array length"
    );

    let mut seen_kdfs: HashSet<KdfAlgo> = HashSet::new();
    let mut seen_combos: HashSet<(String, u32, String)> = HashSet::new();

    for (idx, v) in kat.vectors.iter().enumerate() {
        assert_eq!(
            v.name, "three_forms",
            "every matrix row is the three-forms fixture (row {idx})"
        );
        seen_kdfs.insert(parse_kdf(&v.kdf));
        assert!(
            seen_combos.insert((v.kdf.clone(), v.nonce, v.seed.clone())),
            "duplicate (kdf, nonce, seed) combo at vector {idx}"
        );

        let psbt = replay_row(v);

        // Fixture fence: the three-forms design — a legacy input with
        // its full prev-tx plus two witness-form inputs, in order.
        assert_eq!(psbt.inputs.len(), 3, "row {idx} must have 3 inputs");
        assert!(
            psbt.inputs[0].non_witness_utxo.is_some() && psbt.inputs[0].witness_utxo.is_none(),
            "row {idx}: the legacy input carries NON_WITNESS_UTXO"
        );
        let witness_scripts: Vec<usize> = psbt.inputs[1..]
            .iter()
            .map(|i| i.witness_utxo.as_ref().expect("witness UTXO").script.len())
            .collect();
        assert_eq!(
            witness_scripts,
            vec![22, 34],
            "row {idx}: P2WPKH then P2TR witness UTXOs"
        );
    }

    // The anchored variants sit on the first matrix tuple.
    let anchor = &kat.vectors[0];
    let anchor_tuple = (&anchor.seed, anchor.nonce, &anchor.passphrase, &anchor.kdf);
    let unknown_tuple = (
        &kat.unknown_fields.seed,
        kat.unknown_fields.nonce,
        &kat.unknown_fields.passphrase,
        &kat.unknown_fields.kdf,
    );
    assert_eq!(
        anchor_tuple, unknown_tuple,
        "the unknown_fields variant anchors on the first matrix tuple"
    );
    let combine_tuple = (
        &kat.combine.seed,
        kat.combine.nonce,
        &kat.combine.passphrase,
        &kat.combine.kdf,
    );
    assert_eq!(
        anchor_tuple, combine_tuple,
        "the combine pair anchors on the first matrix tuple"
    );
    assert_eq!(
        kat.combine.a, anchor.signed,
        "combine.a is the signed anchor container"
    );

    // Unknown-fields variant: the full pipeline again, byte-for-byte.
    replay_row(&kat.unknown_fields);
    let done = PartiallySignedTransaction::from_base64(&kat.unknown_fields.finalized)
        .expect("finalized unknown_fields container parses");
    // Every injected opaque pair survives the whole pipeline,
    // byte-for-byte, in its own map.
    assert_eq!(
        done.unknown_global,
        vec![UnknownKv {
            key: vec![0x51, 0xaa, 0xbb],
            value: vec![0x01, 0x02, 0x03],
        }],
        "the global opaque pair must survive"
    );
    assert_eq!(
        done.inputs[1].unknown,
        vec![UnknownKv {
            key: vec![0x52, 0xcc],
            value: vec![0x04, 0x05],
        }],
        "the input-1 opaque pair must survive"
    );
    assert_eq!(
        done.outputs[0].unknown,
        vec![UnknownKv {
            key: vec![0x53, 0xdd, 0xee],
            value: vec![0x06],
        }],
        "the output-0 opaque pair must survive"
    );
    // And the wire transaction is blind to them: identical to the
    // clean anchor row's extraction.
    assert_eq!(
        kat.unknown_fields.hex, anchor.hex,
        "extraction must ignore opaque pairs"
    );

    // Combine pair: re-derive `combined` from `a` plus the synthetic
    // disjoint-signer injection of the row design.
    let a = PartiallySignedTransaction::from_base64(&kat.combine.a).expect("combine.a parses");
    let mut b = PartiallySignedTransaction::from_base64(&kat.combine.a).expect("combine.b parses");
    b.inputs[0]
        .partial_sigs
        .push((PubKey(vec![0x02; 33]), vec![0xbb; 64]));
    b.unknown_global.push(UnknownKv {
        key: vec![0x51, 0x07],
        value: vec![0x09],
    });
    let combined = a.combine(&b).expect("same UNSIGNED_TX combines");
    assert_eq!(
        combined.to_base64(),
        kat.combine.combined,
        "combined stage mismatch"
    );
    // Different keys of one type are all kept: the real partial sig
    // plus the synthetic one, and the extra unknown global pair.
    assert_eq!(
        combined.inputs[0].partial_sigs.len(),
        2,
        "both PARTIAL_SIG entries must be kept"
    );
    assert!(
        combined
            .unknown_global
            .iter()
            .any(|kv| kv.key == vec![0x51, 0x07] && kv.value == vec![0x09]),
        "the synthetic unknown global pair must be kept"
    );

    // Coverage fence: all four KDFs, each at 2 nonces × 2 seeds. The
    // passphrase is forced by the kdf (empty for yubtc, non-empty for
    // the rest — see generate.py), so the (kdf, nonce, seed) triple
    // identifies the row uniquely.
    assert_eq!(
        seen_kdfs.len(),
        4,
        "psbt_vectors.json must cover all 4 KDFs"
    );
    assert_eq!(
        seen_combos.len(),
        16,
        "expected the full 4 KDFs × 2 nonces × 2 seeds matrix"
    );
}
